### ISSUE TITLE
Suggestion: For each new release, please create a release note as an additional asset 

### ISSUE THREAD

**Issue by raindropsfromsky** [GerHobbelt/qiqqa-open-source#8]
Currently, we cannot know what changes are carried out in the latest experimental version (e.g. what are the changes in v82pre8 vis-a-vis v82pre7?)

If the users know the latest features, they can test these features and give feedback.
Thus the Release notes will help all of us in maturing the product faster!

**Suggestion:** 
Please release a text file as **Release notes** with each experimental version; and post it as an additional asset.

**Comment by GerHobbelt** [comment]
Filed as mainline  #176.
